import Head from 'next/head';

import { getApolloClient } from '../lib/apollo-client';
import { gql } from '@apollo/client';

import Header from './component/Header';
import Main from './component/Main';
import Footer from './component/Footer';

export default function Home({ page, themes }) {
    const {title,description} = page;

    console.log(page);
    console.log(themes);

    return (
        <>
            <Head>
                <title>{title} &mdash; {description}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icons/favicon.ico" />
            </Head>
            <div className="siteFlex">
                <Header />
                <Main />
                <Footer />
            </div>
        </>
    );
}

export async function getStaticProps() {
    const apolloClient = getApolloClient();

    const data = await apolloClient.query({
        query: gql`
            query getThemes {
                generalSettings {
                    title
                    description
                }
                allTemalar(first: 10000) {
                    edges {
                        node {
                            temalarId
                            title
                            slug
                            date
                            content
                            featuredImage {
                                node {
                                    sourceUrl
                                    srcSet
                                    mediaDetails {
                                        width
                                        height
                                    }
                                }
                            }
                            Temalar {
                                demoLink
                                hot
                                indirmelinki
                                teknolojiler
                                temaIndirimFiyat
                                temaNormalFiyat
                                themeDoc
                                ucretsiz
                                yeni
                            }
                        }
                    }
                }
            }
        `,
    });

    const page = {
        ...data?.data.generalSettings,
    };

    const themes = data?.data.allTemalar.edges
        .map(({ node }) => node)
        .map((theme) => {
            return {
                ...theme,
                path: `/temalar/${theme.slug}`,
            };
        });

    return {
        props: {
            page,
            themes,
        },
    };
}
